.travis.yml
@rsignell-usgs raised this issue in the mailing list.  We can use travis to generate the HTML and publish the pages automatically.  This PR makes the "merge action"  also a "Publish page step."
There are a few things to do in this PR:
- Activate travis for cf-convention.github.io
- Add a GitHub Token
- Check if the pushing step will work once the Token is in place
Only someone with admin rights can do those steps.
=> Publish pages with travis

.travis.yml
Added some tips from
http://krunoknego.com/2015/03/07/how-to-configure-travis-for-jekyll-github-page/
Will these help overcome the recurring test failures on travis?
=> Update .travis.yml for better performance

.travis.yml, generate.sh
@rsignell-usgs 
- We do not need `NOKOGIRI_USE_SYSTEM_LIBRARIES=true`  because we do not run `html-proofer`.
- No need to define ruby nor to install Jekyll and its gems because we do not need to run Jekyll (we only need to create the main document)
- The `exclude: [vendor]` should go into the jekyll `_config.yml` and not in the `.travis.yml` file.  However, we will need that only if build the whole site with Jekyll on Travis-CI.
Note that we could build the whole site and test it.  However, that is beyond the scope of an auto-publish setup and I believe we should leave that to another PR.
=> Do not push to "${GIT_NAME}"

Data/cf-documents/requirements-recommendations/requirements-recommendations-1.6.html, documents.md, faq.md, latest.md
NB. This references the v1.6 HTML & PDF documents directly in the cf-convention/cf-conventions repo (e.g. http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html). It does not copy the HTML & PDF documents into this repo.
=> Point v1.6 links at AsciiDoc outputs.

Data/cf-documents/requirements-recommendations/requirements-recommendations-1.7.html, documents.md, faq.md, latest.md
Thanks to @painter1 and  @marqh, cf-convention/cf-conventions#62 has been merged, which gets the AsciiDoc-based outputs on a par with the DocBook outputs.
This PR switches the links on the website to use the AsciiDoc-based outputs (e.g. http://cfconventions.org/cf-conventions/cf-conventions.html) so they will automatically benefit from further progress on the 1.7 draft.
=> Point v1.7 links at AsciiDoc outputs.

constitution.adoc, constitution_original.md, governance.md
I have converted the appendix in the white paper giving the terms of reference into constitution.adoc, and made a link to it from the governance page. This is no change in content from the current arrangements. When this has been merged, I will propose the small changes from the governance panel.
=> Add original constitution (from white paper) and a link to it

faq.md, index.md
The link to the NetCDF Library on the Index page is broken. It directs to
https://www.unidata.ucar.edu/packages/netcdf/index.html
but should direct to
https://www.unidata.ucar.edu/software/netcdf/index.html
The links to the Documentation of the UDUnits API in the FAQ are broken. They direct to
https://www.unidata.ucar.edu/software/udunits/udunits-2.2.16/doc/udunits/udunits2lib.html
but should direct to
https://www.unidata.ucar.edu/software/udunits/udunits-current/doc/udunits/udunits2lib.html
Added s to http.
=> Fix links to NetCDF Library and to UDUnits API Doc

faq.md
In the answer to question [My variable depends on the type of surface. How can I specify the surface type?](http://cfconventions.org/faq.html#surface_type_coordinate) there is a link to the Area Type Table. The link is broken. It directs to 
* http://cfconventions.org/Data/cf-standard-names/docs/area-type-table.html 
but should direct to 
* http://cfconventions.org/Data/area-type-table/current/build/area-type-table.html
=> in faq updated url to area type table; fixed #75

Meetings/2018-Workshop.md, Meetings/2019-Workshop.md, Meetings/2020-Workshop.md, Meetings/index.md
@davidhassell and @erget  - Here's a PR for the Meetings pages we discussed in Thursday's call. For the 2020 Workshop page, I mostly just pulled the text from your draft announcement.
I made it a sub-directory (thought about sub-dirs for each year, maybe later if we need them) but I'm not sure I got the navigation stuff right. I tried to follow the patterns I found but don't have Jekyll setup to run locally so haven't tested that it will build properly. I guess Travis builds on PRs and we can see success or failure but not sure we can look at resulting pages.
=> Add Meetings pages for annual workshops and other CF related meetings.

_layouts/default.html
Fixes unresolved references in the meetings pages, which are a step down the tree and thus weren't finding the image and JS assets.
=> Make references absolute

index.md, software.md
An initial stab at adding a CF Software page (see issue #100).
I tried two different ways of formatting the list: a basic Markdown nested list and an HTML collapsable 'details/summary' for each software package. If anyone has a better idea ...
=> Add page for CF Software list

.github/ISSUE_TEMPLATE/defect-issue.md, .github/ISSUE_TEMPLATE/enhancement-issue.md, .github/ISSUE_TEMPLATE/github-problem-issue.md, .github/ISSUE_TEMPLATE/governance-issue.md, .github/ISSUE_TEMPLATE/typo-issue.md, .github/ISSUE_TEMPLATE/update-issue.md, CONTRIBUTING.md
Designed to fast-track just the CONTRIBUTING portion of #103. I'll move todos into an associated issue.
=> Add CONTRIBUTING.md

wkt-proj-4.md
Several links on the page http://cfconventions.org/wkt-proj-4.html
were not working because they were defined as "URL\[URL\]" instead
of "\[URL\]\(URL\)".
=> fixes issues with links on WKT page; fixed #83

governance.md
Add "Team" to "Information Management and Support" and "Former" headings
Move Jeff Painter and Tanya Reshel to "Former"
Add Kyle Halliday and Velimir Mlaker as "Former"
=> Updates to Information Management and Support Team

governance.md
Changing affiliation in the Information Management and Support Team section of the Governance page as per https://github.com/cf-convention/discuss/issues/138
=> Changing affiliation on governance page

discussion.md
Link GitHub archive and correct link to NCAR archive to use https
=> modify mailing list archive on discussion page

conventions_contributors.md
After noticing #287 on the Issue Tracker, I noticed I am not on the list of contributors here and imagine I probably should be due to my infrastructure contributions (I don't think I have contributed in any other more direct way, yet, but hope to do so soon or at least eventually!). Please correct me if I am wrong. If you require some evidence to justify the addition of myself to the list, I can point you to some issues or similar, but hopefully that is not necessary. Thanks.
=> Add Sadie Bartholomew to list of contributors

faq.md
Add some configuration so top-level headers are not included in TOC. 
I also re-added some summary text for each of the FAQ category headers. This text was in the old TOC.
=> Clean up TOC on CF FAQ page

vocabularies.md
Links for v80 were wrong (pointed to v79 instead).
=> Fix link errors for v80 in vocabularies.md

faq.md
Cf. [Link Checker report #370](https://github.com/cf-convention/cf-convention.github.io/issues/370):
> ✗ [404] https://www.unidata.ucar.edu/software/udunits/udunits-current/udunits2lib.html#Examples | Failed: Network error: Not Found
=> Updated a broken link to UDUNITS examples of how to format units strings

software.md
Reverses https://github.com/cf-convention/cf-convention.github.io/pull/389
=> Reactivate link to IOOS online checker

.github/workflows/check_jekyll_build.yml, .github/workflows/check_links.yml
Fixes #424 
With  `actions/checkout@v2` we are getting "node12" deprecation warnings. According to https://github.com/actions/checkoutissues/1047 we need to update to `actions/checkout@v3`, which is what this PR does. With this change the build looks fine for me locally, and the deprecation errors have gone.
=> Update to `actions/checkout@v3`

vocabularies.md
See issue #408 for discussion.
=> Updated the vocabularies page to include links to "current version", and fixing some typos

vocabularies.md
This PR adds a link to the XSD schema file in `vocabularies.html` page, i.e.  implements issue https://github.com/cf-convention/cf-convention.github.io/issues/469.
~~**This PR must be merged after PR https://github.com/cf-convention/cf-convention.github.io/pull/468.**~~ That PR is now merged.
=> Link to XSD schema file on the vocabularies web page

Committees/Conventions_and_Standard_Names/2023-09-29-meeting.md, Committees/Conventions_and_Standard_Names/meeting-minutes.md, Committees/Conventions_and_Standard_Names/template.md, governance.md
Committee minutes 2023-09-29
There is a new link in `goverance.md` that copies the minutes framework used by the Governance Panel. See https://davidhassell.github.io/cf-convention.github.io/
=> Committee minutes 2023-09-29

Meetings/2024-Workshop.md, Meetings/index.md
I have just added the skeleton page for the forthcoming 2024 CF Workshop. 
@larsbarring please, can you review it?
=> Added the 2024 CF Workshop page

software.md
I have recently moved the canonical (working, i.e. being updated as-and-when) location documentation for cf-plot and cf-view from the domain `https://ajheaps.github.io/`, corresponding to hosting under the GitHub user `ajheaps`, to the domain `https://ncas-cms.github.io/` for the user `NCAS-CMS`, after the retirement of our colleague Andy Heaps, who previously managed and hosted thee under his own user space. We wanted these hosted under the NCAS-CMS space in line with our other CF Data Tools libraries (cf-python, cfdm, etc.).
This PR is therefore to update those links. I have also updated the associated summaries in-line with revised straplines (one-sentence summaries) of the libraries, as per the READMEs for the repos in question.
Reviewer(s), if you could please confirm the links work …
=> Software page: updates regarding cf-view & cf-plot packages

Meetings/2024-Workshop.md
I added the link to the SMHI page and added Daniel and Kevin to the organizing committee list. I think we might want to update some of the text to better align with the SMHI page. (Ping - @larsbarring @davidhassell @japamment @efisher008 @erget @kevin-obrien)
=> Update 2024 CF Workshop page with link to SMHI workshop page.

faq.md
I'm making this change at the suggestion of Roy Mendelssohn @rmendels, because of frequent errors from the link-checker
=> change `http` to `https` in FAQ for ERDDAP site

.github/workflows/build_and_deploy_web.yml, .github/workflows/check_links_cron.yml
I have made this change to check links in actual deployed CF page, instead of re-build page from source, every time CRON check links runs. 
1. The CF page, now it's been build from source, and the resulting site files are committed to the `gh-pages` branch, which it's been use by GH to deploy the actual page. 
2. The check actions, download the build page from `gh-pages` branch and check links on contents already build on step 1.
=> Refactor pages build and publish workflow

Meetings/2024-Workshop.md
The preliminary agenda is updated to give a more detailed shcdule with session titles and most chair-persons assigned.
While the file is a github markdown  (`.md`), the table is written in html to allow somewhat more specific formatting.
A test "deployment" is available through [this link (my repo)](https://github.com/larsbarring/cf-convention.github.io/blob/gh-pages/Meetings/2024-Workshop.html), but probably the file will have to be downloaded and then opened with a web browser. 
The intention is to provide more details for each session in the coming week or so.
=> Cf2024 agenda update

Meetings/2024-Workshop.md
This missing closing tag/typo caused the page to just be strangely wrong.
=> Fix missing closing tag in 2024 workshop agenda

Meetings/2024-Workshop.md
Following along with the agenda during the workshop today I noticed a typo. It's a trivial one-word change and whilst elsewhere I'd push it straight to upstream as a lone commit instead of raising a PR, I don't want to bypass our workflows, so please can someone approve and merge? Thanks.
=> CF Workshop 2024 page: fix typo in talk name

.lychee/config.toml
The version 86 of standard names tables has some issues generating the KWIC file format.
The GITHUB project feature has been deleted from the CF-Conventions
=> Putting in quarantine new links errors

Meetings/2020-Workshop.md
Testing pushing changes to the CF website through GitHub pages (Good Housekeeping session CF workshop 2024).
=> Add EF to authors for 2020-Workshop.md

software.md
=> Add CDO to the CF-aware software

Meetings/2024-Workshop.md
Remove cancelled hackathon (Erin Turnball, Localized metadata & CF/ERDDAP) from workshop schedule.
=> Remove localization hackathon 2024-Workshop.md

vocabularies.md
Added the NERC Vocab server as a temporary measure to start including this source to the vocabularies page on the website. I have added links for standard names, area types and regions list but also CF attributes (please comment if you do not want this on the website as currently has no updating mechanism and there are other vocabularies which are not shown here)
=> WIP: Add nvs link

wkt-proj-4.md
see [conventions issue 537](https://github.com/cf-convention/cf-conventions/issues/537)
=> Bring `WKT/PROJ.4` up to date, provide links to csv appendices, correct the markup

Governance/InfoMgmt/2024-03-11-meeting.md, Governance/InfoMgmt/2024-06-05-meeting.md, Governance/InfoMgmt/2024-09-03-meeting.md, Governance/InfoMgmt/2024-12-03-meeting.md, Governance/InfoMgmt/2025-03-04-meeting.md, Governance/InfoMgmt/meeting-minutes.md, Governance/InfoMgmt/template.md, governance.md
=> Add notes from all CF Info Mgmt and Support Team meetings to date.

index.md
I have updated the announcement message to advertise the 2025 CF workshop. It looks like this
=> announcement of 2025 CF workshop

Meetings/2025-Workshop.md, Meetings/index.md, index.md
I have added a few links to the registration form for the workshop
- On the banner on the home page
- On the workshops main page
- On the 2025 workshop page
=> links to register for workshop

Meetings/2025-Workshop.md
Last year at the workshop, when myself or @erget (and I think @cofinoa) were editing the agenda table, having it in html made things a little difficult. Where messing up a closing tag caused the whole page to kinda break.
If folks are interested, this converts that table to be markdown (with some `<br />` tags in the content), it also adds the bootstrap3 table classes so that it renders nicely.
=> Convert 2025 workshop page to "pure" markdown

Meetings/2025-Workshop.md
A trivial change to update a title in the workshop agenda (sorry I was on leave last week so have only just had a chance to update the title confirmed by Jack).
@cf-convention/info-mgmt: please can someone merge this ASAP so it is there in time for the workshop start in less than a few hours! Thanks.
=> Workshop 2025 agenda: add confirmed title for Science Talk
