.travis.yml

@rsignell-usgs I am learning on the job here.  My setup is much simpler!
If this one does not work we can try:
`git push --force --quiet "https://${GH_TOKEN}@github.com/${GIT_NAME}/cf-convention.github.io.git"`

Testing another push command

---

Data/cf-documents/requirements-recommendations/requirements-recommendations-1.7.html

mattben had already made the changes in the text for ticket 31 - thanks.

altered title of 2.5.1

---

Data/cf-conventions/cf-conventions-1.6/docbooksrc/appendix-h.xml

Fixes non-ascii quotation character

---

Data/cf-conventions/cf-conventions-1.6/docbooksrc/appendix-h.xml

- Replaces non-ASCII quotation with ASCII quotations for all examples in
appendix H

Replaces quotes for all examples

---

governance.md

Please could you merge this branch into the master

implemented changes to committee membership

---

governance.md

Some updates to the governance.md file and rebased David Hassell's
changes that haven't made it into master yet.

Update governance.md (take two)

---

governance.md

Adding Fran Eggleton (CEDA) to Information Management and Support

Added Fran Eggleton (CEDA)

---

.github/workflows/check_jekyll_build.yml
Gemfile
README.md
_config.yml

This PR adds a GitHub Action to check the Jekyll build whenever a PR is created or updated.

Add GitHub Action to check Jekyll build of docs on on all PR checkins.

---

constitution.md

The changes are summarised in an issue in this repository with the same title

changes to the CF constitution proposed by the governance panel

---

rules.md

Add rules for updating the CF data model

---

.github/workflows/check_jekyll_build.yml

GitHub Action for testing PRs is broken. Discussion and fix in PR #103. That PR may take awhile to get merged so pulling this fix out on its own.
@erget - Can you review this and merge if it looks good?

Fix GHA for testing PRs (see discussion in #103)

---

Meetings/2020-Workshop.md

Just minor fixes and some style modifications

Minor style modifications and fixes

---

Meetings/2020-Workshop.md

Updating funding agencies. 
@ethanrd this PR replaces PR #112

Updating funding agencies for 2020 CF Workshop

---

_layouts/default.html

Remove privacy notice

---

governance.md

Update committee membership and add the end date of the current members' terms

People210113

---

governance.md

Three new members have been added to the CF Committee.
Could someone else from @cf-convention/gov-panel review and merge?

Add new members of CF Committee to list in the governance page.

---

Governance/GovPanel/2021-02-10-meeting.md
Governance/GovPanel/meeting-minutes.md

Could someone else from @cf-convention/gov-panel review and merge? - Thanks

Add 2021-02-10 CF Governance Panel meeting notes

---

faq.md

Typo "make"

---

Meetings/2021-Workshop.md

Updating the presentation on OceanGliders-1.0

2021 workshop OG-1.0

---

Meetings/2021-Workshop.md

Update CF Workshop web page with suggested topics for breakout sessions

---

documents.md
faq.md
latest.md
requirements-and-recommendations.md
software.md

Update references and links for 1.9

Updates for releases of CF-1.9

---

Meetings/2021-Workshop.md

* New DOI breakout session
* Link to Google Drive folder
* Link to breakout session descriptions
@castelao  - I couldn't persuade GitHub to add you as a reviewer, so I'm doing it the old fashioned way!

2021 workshop agenda updates

---

Meetings/2021-Workshop.md

I'm adding IS-ENES3 as oficial support for the CF workshop. The IFCA support is for the Zoom license

Adding acknowledgments to 2021 workshop 

---

Meetings/2021-Workshop.md

Minor updates in advance of next week's meeting.

Update with virtual meeting info

---

Meetings/2021-Workshop.md

Change TBD for Governance presentation

Last minute update

---

_layouts/default.html

Code stolen from @cofinoa.
Closes #183

Add "Edit on GitHub" badge

---

Training/2022-Training-Workshop.md
Training/index.md

Training tab on website, and placeholder for 2022 training workshop

---

Meetings/2022-Workshop.md

Provisional agenda for the 2022 workshop.

Workshop agenda 2022

---

Meetings/2022-Workshop.md

Hi @japamment, @ngalbraith and @rmendels - is this I-ADOPT link OK for the agenda?

Workshop 2022: I-ADOPT URL

---

Meetings/2022-Workshop.md

On-line access zoom link placeholder

on-line access zoom link placeholder

---

conventions.md

Update conformance version in `conventions.md`

Release CF-1.10 (part 2)

---

Data/Trac-tickets/119.html
Data/Trac-tickets/123.html
Data/Trac-tickets/138.html

I didn't modify the correct part of the HTML on the last attempt

fix navigation between tickets

---

Meetings/2022-Workshop.md

Added talk title on second day

Updating 2022 CF Workshop agenda

---

Training/2022-Training-Workshop.md

Fixing the link to IS-ENES logo

Some fixings on training page

---

Training/2022-Training-Workshop.md
Training/index.md

Add links to the YouTube channel

Reference the YouTube channel from Training pages

---

Meetings/2022-Workshop.md

I have added the links to the Zoom Rooms for the 2022 CF Workshop meeting

Added Zoom Room Links

---

.github/workflows/check_links.yml

Attempts to fix the failing link checker

try bumping create issue gh action version

---

.github/workflows/check_links.yml

Change check links to cron based

---

Meetings/2022-Workshop.md

Update 2022 CF Workshop rooms for hackatons

Update 2022 CF Workshop rooms for hackatons

---

Meetings/2022-Workshop.md

Update 2022 CF Workshop Meeting

---

_layouts/default.html

This should fix #206 which is caused by our renaming `master` to `main`.

Update master --> main

---

CONTRIBUTING.md
README.md
about-trac.md
constitution.md
discussion.md
faq.md
governance.md
index.md
latest.md
software.md
vocabularies.md
wkt-proj-4.md

Change links to markdown files in this repo to us ".md" extension so link checker is happy.
Also fix some broken reference links.

Fix links to ".md" files (for link checker). Fix broken reference links.

---

Data/cf-standard-names/current/xsl/html/cf-standard-name-table-1.3.xsl

This Pull request make it possible to:
- Search standard_name aliases.
- Search (only) canonical units
It also adds a text box that explains how advance searches (regular expressions and logical linked word list) can be used to query the table.
- https://github.com/cf-convention/cf-convention.github.io/issues/59 (alias search)
- #200 #27 (units search)
- The changes include a refactoring of the javascript code to make it more readable/maintainable (sorry for the reviewers).
- The implementation is rudimentary javascript without any library, so not the prettiest but it's lightweight.
- To reduce the amount of changes introduced by this PR we could remove:
- The python script `generate_html.py` that I used to generate the html (needed to create the demonstrator).
- The html itself, in case …

ENH: Enable alias lookup and units lookup

---

faq.md

Fixed two dead links in the faq.md, as discussed in #380. Also updated most (all?) local links within the document. Also some really minor textual changes, e.g to the UDUNITS units examples (where the direct link into the specific section did not work properly).
@JonathanGregory would you be able to review (and merge when/if happy)?

Updated two dead external links, and fixed several local links.

---

constitution.md
governance.md

See [issue 384](https://github.com/cf-convention/cf-convention.github.io/issues/384)

fix broken links in constitution.md and governance.md

---

software.md

See https://github.com/cf-convention/cf-convention.github.io/issues/386

comment out text to IOOS compliance checker because of broken link

---

discussion.md
standard_name_rules.md
vocabularies.md

See https://github.com/cf-convention/cf-convention.github.io/issues/388

change links to CEDA vocab editor

---

discussion.md

change vocab-editor to vocab_editor!

fix broken link to resolved proposals

---

vocabularies.md

fix HTML error in lnk to current discuss issues

---

faq.md

See https://github.com/cf-convention/cf-convention.github.io/issues/296

Update and replace lists to mailing list

---

governance.md

updates to committee

---

Data/cf-conventions/cf-conventions-1.11/cf-conventions.html

Fix for revision history in published 1.11 documents

Fix for revision history in published 1.11 documents

---

software.md

- Closes #361
- My markdown formatter also fixed some markdown styling

Add xCDAT and cf_xarray to `software.md`

---

conventions_contributors.md

Fixes #438
New contributors to the conventions in discussions leading to 1.11

new contributors from conventions issues

---

LICENSE.md

Add LICENSE.md file to specify CC0 license

---

governance.md

Welcome to the CF info-mgmt team Gui @castelao!
Could someone else on the @cf-convention/gov-panel review and merge? Thanks!

Add Gui to the CF Info Mgmt Team member list on governance page

---

_layouts/default.html

See issue #182, and in particular [this comment](https://github.com/cf-convention/cf-convention.github.io/issues/182#issuecomment-1983550340)

Added license text to the footer.

---

Governance/GovPanel/2024-03-04-meeting.md
Governance/GovPanel/meeting-minutes.md

@cf-convention/gov-panel - Please review and merge if looks good.

Add notes from 2024-03-04 meeting of the CF Governance Panel.

---

Data/schema-files/cf-standard-name-table-2.0.xsd

Change "first_published_date" to "first_published"

---

Meetings/2024-Workshop.md

Updated agenda with speakers and titles, and speakers' ffiliation

Cf2024 update agenda

---

discussion.md
index.md
vocabularies.md

change from `discuss` to `vocabularies` issues

---

CF-beta/CF-beta1.html
CF-beta/CF-beta2.html
CF-beta/CF-beta3.html
CF-beta/CF-beta5.html
CF-beta/index.md
GDT/index.md
conventions.md

See https://github.com/cf-convention/cf-convention.github.io/issues/508

Add GDT and CF-beta versions

---

projects-activities.md

Cleanup of "projects using CF page": removed unused acronyms from list.

Update of PR #503

---

Meetings/2024-Workshop.md

Could someone review and merge if OK @efisher008 @davidhassell

Update cf2024 page

---

Meetings/2024-Workshop.md

Adding CSIC to IFCA affiliation and fixing Jose Manuel's position

Fix IFCA affiliation and em> fragment

---

faq.md

Update FAQ for GitHub Discussions

---

governance.md

as agreed by the governance panel

add Ellie Fisher to the committee

---

discussion.md

improve discussion archive links

---

Governance/GovPanel/2025-12-05-meeting.md
Governance/GovPanel/meeting-minutes.md

Add notes from 5 Dec 2025 CF Governance Panel meeting.

---

Governance/GovPanel/2024-12-05-meeting.md

Fix file name and some text (chg "2025" to "2024").

Fix to 2024-12-05 Gov Panel mtg notes.

---

governance.md

committee update

---

Governance/GovPanel/2025-06-12-meeting.md
Governance/GovPanel/meeting-minutes.md

Add notes from the 2025-06-12 meeting of the CF Governance Panel.

---

Meetings/2025-Workshop.md
Meetings/index.md

For review - @japamment @cofinoa @erget @davidhassell @efisher008 @castelao @kevin-obrien @larsbarring @lhmarsden @sadielbartholomew

Add 2025 CF Workshop web page

---

Data/trac.html
about-trac.md
discussion.md

Further improvements to Archive links on the `discussion` page
